SUMMARY = "Plugin for accessing test session metadata"
DESCRIPTION = "pytest-metadata is a plugin for pytest that provides access to test session metadata."
AUTHOR = "Dave Hunt <dhunt@mozilla.com>, Jim Brännlund <jimbrannlund@fastmail.com>"
HOMEPAGE = "https://github.com/pytest-dev/pytest-metadata"
BUGTRACKER = "https://github.com/pytest-dev/pytest-metadata/issues"
SECTION = "development"
LICENSE = "MPL-2.0"

CVE_PRODUCT = ""
