SUMMARY = "A pytest plugin to report test results as JSON "
DESCRIPTION = "This pytest plugin creates test reports as JSON. This makes it easy to process test results in other applications."
AUTHOR = "numirias <numirias@users.noreply.github.com>"
HOMEPAGE = "https://github.com/numirias/pytest-json-report"
BUGTRACKER = "https://github.com/numirias/pytest-json-report/issues"
SECTION = "development"
LICENSE = "MIT"

CVE_PRODUCT = ""
