SUMMARY = "pytest plugin to abort hanging tests"
DESCRIPTION = "This plugin will time each test and terminate it when it takes too long. Termination may or may not be graceful, please see below, but when aborting it will show a stack dump of all thread running at the time. This is useful when running tests under a continuous integration server or simply if you don’t know why the test suite hangs."
AUTHOR = "Floris Bruynooghe <flub@devork.be>"
HOMEPAGE = "https://github.com/pytest-dev/pytest-timeout"
BUGTRACKER = "https://github.com/pytest-dev/pytest-timeout/issues"
SECTION = "development"
LICENSE = "MIT"

CVE_PRODUCT = ""
