SUMMARY = "importlib_metadata is a library to access the metadata for a Python package."
DESCRIPTION = "importlib_metadata is a library which provides an API for accessing an installed package’s metadata (see PEP 566), such as its entry points or its top-level name."
AUTHOR = "Jason R. Coombs <jaraco@jaraco.com>"
HOMEPAGE = "https://github.com/python/importlib_metadata"
BUGTRACKER = "https://github.com/python/importlib_metadata/issues"
SECTION = "development"
LICENSE = "Apache-2.0"

CVE_PRODUCT = ""
